package me.kordun.enums;

public enum TransactionEvent {
	AUTHORIZATION_START,
	AUTHORIZATION_FINISHED,
	PRE_AUTHORIZATION_START,
	PRE_AUTHORIZATION_FINISHED,
	CAPTURE_STARTED,
	CAPTURE_FINISHED,
	VOID_STARTED,
	VOID_FINISHED,
	REFUND_STARTED,
	REFUND_FINISHED,
	REDIRECTED_TO_ACS,
	RETURNED_FROM_ACS,
	REDIRECT_TO_MERCHANT,
	FAILED_3DSECURE,
	MANUAL_CAPTURE_IN_BO,
	MANUAL_REFUND_IN_BO,
	SSL_OPERATION_NOT_ALLOWED,
	CAPTURE_FAILED,
	REFUND_FAILED,
	PAYMENT_PAGE_LOADED
}